#!/usr/bin/env python
import sys,os

Import('env')
env.AppendUnique(CPPPATH=['.', 'math', 'framework', 'opengl'])
tmpEnv = env.Copy()
tmpEnv.AppendUnique(CPPPATH=['glew/include'])

#Build glew
os.system("make -C glew")

src_opengl="""opengl/light.cpp
       opengl/pixelformat.cpp
       opengl/effectCG.cpp
       opengl/image.cpp
       opengl/imageloader.cpp
       opengl/imageloader_dat.cpp
       opengl/ressourcemanager.cpp
       opengl/texturemanager.cpp
       opengl/shadermanager.cpp
       opengl/geometricbatch.cpp
       opengl/fbo.cpp
       opengl/trackball.cpp
       opengl/texture.cpp
       opengl/startypes.cpp
       opengl/textureunit.cpp
       opengl/texture2d.cpp
       opengl/texture3d.cpp
       opengl/font.cpp 
       opengl/pbuffer.cpp 
       opengl/camera.cpp
       opengl/renderer.cpp
       opengl/mesh.cpp 
       opengl/vertexbuffer.cpp
       opengl/object3d.cpp 
       opengl/material.cpp 
       opengl/shaderCG.cpp 
       opengl/shader.cpp"""

#src_framework="""framework/application.cpp
#              framework/application.h
#              framework/exception.h
#              framework/timer.cpp
#              framework/timer.h"""
src_framework="""framework/application.cpp
              framework/timer.cpp"""

#tmpEnv.Library('frameworkGL', Split(src_framework)+Split(src_opengl))
tmpEnv.SharedLibrary('frameworkGL', Split(src_framework)+Split(src_opengl))
