#!/usr/bin/env python
import sys, os

sdl_env = Environment()
freetype_env = Environment()

if sys.platform == 'linux2' or sys.platform == 'linux-i386':
	#z lib
	z_lib = ['z']
	z_libpath = ['/usr/lib']
	z_include = ['/usr/include']

env = Environment(TARGS=COMMAND_LINE_TARGETS,
		  tools=['default', 'generic', 'opengl', 'cg', 
			 'sdl', 'sdl_image', 'freetype'],
		  toolpath=['.', '..', '../admin']
		 )
#Framework installation path
framework_lib = ['frameworkGL', 'GLEW']
framework_libpath = [os.path.join(env['PREFIX'],'lib')]
framework_include = [os.path.join(env['PREFIX'],'include/starengine')]

env.AppendUnique(CPPPATH = framework_include+z_include)
env.AppendUnique(LIBPATH = framework_libpath+z_libpath)
env.PrependUnique(LIBS = framework_lib+z_lib)

#Create test programs
SConscript('testTexture/SConscript', exports = 'env')
SConscript('testCG/SConscript', exports = 'env')
SConscript('volrend/SConscript', exports = 'env')
SConscript('volrendCG/SConscript', exports = 'env')
SConscript('testBatch/SConscript', exports = 'env')
SConscript('clipmap/src/SConscript', exports = 'env')

env.Alias('testTexture', 'testTexture/src/testTexture')
env.Alias('testCG', 'testCG/src/testCG')
env.Alias('volrend' 'volrend/src/volrend')
env.Alias('volrendCG' 'volrendCG/src/volrendCG')
env.Alias('testBatch', 'testBatch/src/testBatch')
env.Alias('clipmap', 'clipmap/src/clipmap')
