
struct vertout {
  float4 hpos : POSITION;
  float4 color : COLOR;
  float4 texCoord : TEXCOORD0;
};

vertout main(float3 position : POSITION,
             float4 color : COLOR,
	         uniform float4x4 mvp,
             uniform float4 scaleTranslate,
             uniform float4 scaleTranslateTex,
             uniform sampler2D heightmap)
{
  vertout OUT;

  float2 uv = position.xz*scaleTranslateTex.xy+scaleTranslateTex.zw;
  float z = tex2Dlod(heightmap, float4(uv, 0, 1)).x;
  float2 worldPos = position.xz*scaleTranslate.xy+scaleTranslate.zw;
  z = 0;
  OUT.hpos = mul(mvp, float4(worldPos.x, z*30, worldPos.y, 1));
  OUT.color = color;
  OUT.color = float4(uv, 0, 1);
  OUT.texCoord = float4(uv, 0, 1);

  return OUT;
}
