#!/usr/bin/env python
import sys

sdl_env = Environment()
freetype_env = Environment()

if sys.platform == 'linux2' or sys.platform == 'linux-i386':
	#z lib
	z_lib = ['z']
	z_libpath = ['/usr/lib']
	z_include = ['/usr/include']
	#Framework
	framework_lib = ['frameworkGL']
	framework_libpath = ['#lib']
	framework_include = ['#include']

env = Environment(TARGS=COMMAND_LINE_TARGETS,
		  tools=['default', 'generic', 'opengl', 'cg', 
			 'sdl', 'sdl_image', 'freetype'],
		  toolpath=['.', 'admin']
		 )
env.Append(CPPPATH = framework_include+z_include)
env.Append(LIBS = framework_lib+z_lib)
env.Append(LIBPATH = framework_libpath+z_libpath)

SConscript('framework/SConscript', exports = 'env')
#SConscript('reflection/SConscript', exports = 'env')
#SConscript('pbuffer/SConscript', exports = 'env')
#SConscript('perpixellight/SConscript', exports = 'env')
SConscript('testTexture/SConscript', exports = 'env')
SConscript('testCG/SConscript', exports = 'env')
SConscript('volrend/SConscript', exports = 'env')
SConscript('volrendCG/SConscript', exports = 'env')

print env['ARGS']['prefix']
