#!/usr/bin/env python
import sys, os

sdl_env = Environment()
freetype_env = Environment()

if sys.platform == 'linux2' or sys.platform == 'linux-i386':
	#z lib
	z_lib = ['z']
	z_libpath = ['/usr/lib']
	z_include = ['/usr/include']

env = Environment(TARGS=COMMAND_LINE_TARGETS,
		  tools=['default', 'generic', 'opengl', 'cg', 
			 'sdl', 'sdl_image', 'freetype'],
		  toolpath=['.', 'admin']
		 )
#Framework installation path
framework_lib = ['frameworkGL', 'GLEW']
framework_libpath = [os.path.join(env['PREFIX'],'lib')]
framework_include = [os.path.join(env['PREFIX'],'include/starengine')]

env.AppendUnique(CPPPATH = framework_include+z_include)
env.AppendUnique(LIBPATH = framework_libpath+z_libpath)
env.AppendUnique(LIBS = z_lib+['GLEW'])

#Create library
SConscript('framework/SConscript', exports = 'env')
